site_name: FEECC - quality control system
repo_name: 'Multi-Agent-io/feecc-workbench-daemon'
repo_url: 'https://github.com/Multi-Agent-io/feecc-workbench-daemon'
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
#  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
#    - navigation.tabs
#    - navigation.tabs.sticky
    - toc.follow
    - navigation.top
plugins:
  - search
nav:
  - Welcome: "index.md"
  - Customer:
    - Descriprion: "customer/description.md"
    - Cases: "customer/cases.md"
    - Products: "customer/products.md"
    - Equipment: "customer/equipment.md"
  - Developer:
    - Introduction: "developer/introduction.md"
    - Workbench:
      - Workbench Components: "developer/workbench_and_components.md"
      - Workbench Daemon: "developer/feecc-workbench-daemon.md"
      - HID Reader: "developer/feecc-hid-reader-daemon.md"
      - Workbench Frontend: "developer/feecc-workbench-frontend.md"
    - Gateway:
      - Cameraman: "developer/feecc-cameraman.md"
      - IPFS Gateway: "developer/feecc-ipfs-gateway.md"
      - Printer Server: "developer/feecc-printer-server.md"

    - QAD Workbench: "developer/qad-workbench.md"
    - Aanlytics Backend: "developer/feecc-analytics-backend.md"
    - Aanlytics Frontend: "developer/feecc-analytics-frontend.md"